#dvc.yaml
stages:
  get_data:
    cmd: python part2_dvc/scripts/data.py
    deps: 
      - part2_dvc/scripts/data.py
    params: 
      - index_col
    outs:
      - part2_dvc/data/initial_data.csv
  fit_model:
    cmd: python part2_dvc/scripts/fit.py
    deps:
      - part2_dvc/scripts/fit.py
      - part2_dvc/data/initial_data.csv
    params:
      - one_hot_drop
      - n_estimators
      - random_state
      - target_col
    outs:
      - part2_dvc/models/fitted_model.pkl
  evaluate_model:
    cmd: python part2_dvc/scripts/evaluate.py
    deps:
      - part2_dvc/scripts/evaluate.py
      - part2_dvc/data/initial_data.csv
      - part2_dvc/models/fitted_model.pkl
    params:
      - target_col
      - n_splits
      - random_state
      - shuffle
      - n_jobs
      - metrics
    outs:
      - part2_dvc/cv_results/cv_res.json