#part2_dvc/params.yaml
index_col: 'id'
one_hot_drop: 'if_binary'
n_estimators: 100
random_state: 42
target_col: 'price'
n_splits: 5
shuffle: True
n_jobs: -1
metrics: ['neg_mean_absolute_error', 'r2', 'neg_mean_absolute_percentage_error']